### ISSUE TITLE
Can't connect between UCCX-Chat-Connector and Socialminer

### ISSUE THREAD

**Issue by doanphong1208** [bdm1981/uccx-chat-connector#2]
Can I get post messenger from FaceBook on UCCX-Chat-Connector, but I can not know if UCCX-Chat-Connector is connected to Socialminer?
![image](https://user-images.githubusercontent.com/22117227/40231900-fd1e1cc6-5ac6-11e8-9a32-2599b2bf71c3.png)
Can you help me ?

**Comment by doanphong1208** [comment]
Can anyone tell me what I'm doing wrong? Thanks!

**Comment by bdm1981** [comment]
Hi @doanphong1208 

Are you able to access social miner from the system that is running the connector? Does web chat work? Did you set the CSQ value in the .env file to match one of the chat queues on your system?

- Brad

**Comment by doanphong1208** [comment]
Yes, I can access socialminer from the system that is running the connector, and properly queue. Webchat works very well. But I can't sent message from FB to Agent Finnesse.

**Comment by bdm1981** [comment]
Does the FB user receive the auto response from the connector? If you could email me a copy of your .env configuration file, I can take a look. Just delete the FB token from it: bmcallis@cisco.com

**Comment by doanphong1208** [comment]
Hi @bdm1981 
I sent mail to bmcallis@cisco.com by doanphongtn94@gmail.com.
Thanks for your support.

**Comment by bdm1981** [comment]
Permissions were adjusted on the FB application to allow test accounts to leverage the connector.
